name    'winpuppet'
version '0.0.1'
source 'git@github.com:mastoj/winpuppet.git'
author 'Tomas Jansson'
license 'The MIT License (MIT)'
summary 'Sample Windows manifest'
description 'Sample Windows manifest'
project_page 'https://github.com/mastoj/winpuppet'
dependency 'joshcooper/powershell'